### ISSUE TITLE
Selecting values in radio/checkbox inputs trigger a `Click` event

### ISSUE THREAD

**Issue by vincent-psarga** [Smartesting/gravity-data-collector#2]
**Describe the bug**

When using the keyboard to navigate to an `<input type="radio" >` (or `checkbox`), two events are generated: one with a type `click`, one with a type `change`.

**To Reproduce**

For the `radio` input:
- Use the sandbox page provided in this repo
- Use tabulation to activate the radio input
- Press arrow up/down
- Two events are shown in the console:

![Capture d’écran 2022-07-20 à 16 41 20](https://user-images.githubusercontent.com/186248/180010873-787c7c7b-4145-4da1-b02d-a5f73c562287.png)

For the `checkbox` input:
- Same two first steps
- Use the "space" keyboard key to select an option
- Once again, two events are generated (including a `Click` one)

**Expected behavior**

Ideally, instead of a `click` event, I'd expect a `keypress` event (or `keydown`, whatever) to be displayed.
Less ideally, I'd expect a single event with a type `Change`

**Comment by aymeric-cr** [comment]
FYI

https://www.quirksmode.org/dom/events/click.html

> The click event fires when the user clicks on an element OR activates an element by other means (i.e. the keyboard) ... “click” event is really a misnomer: it should be called the “activate” event.
